In [1]:
import numpy as np
import tensorflow as tf
from tensorflow.keras.layers import BatchNormalization, LayerNormalization

In [2]:
np.set_printoptions(precision=3, suppress=True)

# ----------------------------------------------------------------------
# 1. Create a small dataset (random input values)
# ----------------------------------------------------------------------
# Shape: (batch_size=4, features=5) -> 4 "samples", each with 5 features
np.random.seed(42)
data = np.random.uniform(low=0, high=100, size=(4, 5)).astype(np.float32)

print("=" * 60)
print("Original Input Values")
print("=" * 60)
print(data)

Original Input Values
[[37.454 95.071 73.199 59.866 15.602]
 [15.599  5.808 86.618 60.111 70.807]
 [ 2.058 96.991 83.244 21.234 18.182]
 [18.34  30.424 52.476 43.194 29.123]]


In [3]:
# ----------------------------------------------------------------------
# 2. Apply Batch Normalization
# ----------------------------------------------------------------------
# BatchNorm normalizes each FEATURE (column) using the mean/variance
# computed ACROSS THE BATCH (all 4 samples), for that feature.
bn_layer = BatchNormalization()
# training=True forces it to use the current batch's statistics
# instead of the (untrained) running averages.
bn_output = bn_layer(data, training=True)

print("\n" + "=" * 60)
print("Batch Normalization Output")
print("=" * 60)
print(bn_output.numpy())


Batch Normalization Output
[[ 1.512  0.952 -0.051  0.865 -0.804]
 [-0.219 -1.284  0.957  0.881  1.686]
 [-1.291  1.     0.703 -1.563 -0.688]
 [-0.002 -0.668 -1.609 -0.183 -0.194]]


In [4]:
# ----------------------------------------------------------------------
# 3. Apply Layer Normalization
# ----------------------------------------------------------------------
# LayerNorm normalizes each SAMPLE (row) using the mean/variance
# computed ACROSS THE FEATURES of that single sample.
ln_layer = LayerNormalization()
ln_output = ln_layer(data)

print("\n" + "=" * 60)
print("Layer Normalization Output")
print("=" * 60)
print(ln_output.numpy())


Layer Normalization Output
[[-0.68   1.406  0.614  0.131 -1.472]
 [-1.019 -1.329  1.229  0.39   0.729]
 [-1.107  1.379  1.019 -0.605 -0.685]
 [-1.379 -0.361  1.496  0.714 -0.471]]


In [5]:
# ----------------------------------------------------------------------
# 4. Sanity check: show the stats each method actually normalizes over
# ----------------------------------------------------------------------
print("\n" + "=" * 60)
print("Quick check of normalization axis")
print("=" * 60)
print("Per-FEATURE mean across the batch (BatchNorm's target ~0):")
print(bn_output.numpy().mean(axis=0))
print("\nPer-SAMPLE mean across features (LayerNorm's target ~0):")
print(ln_output.numpy().mean(axis=1))


Quick check of normalization axis
Per-FEATURE mean across the batch (BatchNorm's target ~0):
[-0.  0. -0. -0.  0.]

Per-SAMPLE mean across features (LayerNorm's target ~0):
[-0. -0.  0.  0.]


In [6]:
# ----------------------------------------------------------------------
# 5. Explanation
# ----------------------------------------------------------------------
explanation = """
Comparison of Batch Normalization and Layer Normalization
------------------------------------------------------------
- Batch Normalization (BN) normalizes each feature (column) using the
  mean and variance computed ACROSS ALL SAMPLES in the current batch.
  This keeps activations at a stable scale during training, which lets
  the network use higher learning rates and converge faster.
- Layer Normalization (LN) normalizes each sample (row) using the mean
  and variance computed ACROSS THAT SAMPLE'S OWN FEATURES, independent
  of any other sample in the batch.
- Key difference: BN's statistics depend on the batch (so results
  change with batch size and are unstable for batch size = 1), while
  LN's statistics depend only on a single sample (so it works
  identically regardless of batch size) - this is why LN is preferred
  in RNNs/Transformers where batch statistics are less meaningful.
"""
print(explanation)


Comparison of Batch Normalization and Layer Normalization
------------------------------------------------------------
- Batch Normalization (BN) normalizes each feature (column) using the
  mean and variance computed ACROSS ALL SAMPLES in the current batch.
  This keeps activations at a stable scale during training, which lets
  the network use higher learning rates and converge faster.
- Layer Normalization (LN) normalizes each sample (row) using the mean
  and variance computed ACROSS THAT SAMPLE'S OWN FEATURES, independent
  of any other sample in the batch.
- Key difference: BN's statistics depend on the batch (so results
  change with batch size and are unstable for batch size = 1), while
  LN's statistics depend only on a single sample (so it works
  identically regardless of batch size) - this is why LN is preferred
  in RNNs/Transformers where batch statistics are less meaningful.

