In [28]:
np.set_printoptions(precision = 3, suppress = True)

x = np.array([ [1.0, 2.0, 30.0], 
              [2.0, 4.0, 32.0], 
              [3.0, 8.0, 34.0],
              [4.0, 8.0, 34.0]
             ]
             )

print(" Input Data : \n", x)


 Input Data : 
 [[ 1.  2. 30.]
 [ 2.  4. 32.]
 [ 3.  8. 34.]
 [ 4.  8. 34.]]


In [29]:
eps = 1e-5

mean = x.mean(axis = 0) # mean of each column
var = x.var(axis = 0)  # variance of each column

print(" Mean Per Feature: ", mean)
print(" Variance Per Feature :", var)

x_hat = (x - mean)/ np.sqrt(var + eps)
print("\n Normalized x (x_hat) : \n", x_hat)
print("\n New Mean Per Feature (should be  -0): ", x_hat.mean(axis = 0))
print(" New Variance Per Feature (should be -1): ", x_hat.var(axis = 0))

 Mean Per Feature:  [ 2.5  5.5 32.5]
 Variance Per Feature : [1.25 6.75 2.75]

 Normalized x (x_hat) : 
 [[-1.342 -1.347 -1.508]
 [-0.447 -0.577 -0.302]
 [ 0.447  0.962  0.905]
 [ 1.342  0.962  0.905]]

 New Mean Per Feature (should be  -0):  [0. 0. 0.]
 New Variance Per Feature (should be -1):  [1. 1. 1.]


In [30]:
gamma = np.ones(3)
beta = np.zeros(3)

out = gamma* x_hat + beta
print(" Output After gamma/beta : \n", out)

 Output After gamma/beta : 
 [[-1.342 -1.347 -1.508]
 [-0.447 -0.577 -0.302]
 [ 0.447  0.962  0.905]
 [ 1.342  0.962  0.905]]


In [31]:
mean_in = x.mean(axis  = 1, keepdims = True)
var_in = x.var(axis = 1, keepdims = True)

x_hat_in = (x - mean_in)/ np.sqrt(var_in + eps)
print("LayerNorm Normalized x : \n", x_hat_in)
print("\n row means (should be -0) : ", x_hat_in.mean(axis = 1))
print(" row vars (should be -1) : ", x_hat_in.var(axis = 1))
                 

LayerNorm Normalized x : 
 [[-0.744 -0.67   1.414]
 [-0.779 -0.633  1.412]
 [-0.883 -0.515  1.398]
 [-0.852 -0.551  1.404]]

 row means 9should be -0) :  [ 0.  0.  0. -0.]
 row vars (should be -1) :  [1. 1. 1. 1.]
